Completed html-forms exercise
DavidKyong/c0523-code-solutions pull request #22
Opened 2023-05-16 03:02 UTC by DavidKyong

<img width="422" alt="Screenshot 2023-05-15 at 7 57 27 PM" src="https://github.com/DavidKyong/c0523-code-solutions/assets/77517004/ed4f0d3e-9e0f-4bd3-a105-7b94f992e6a0">

2023-05-16 17:27 UTC, shawnkost requested changes
Some changes requested here David!

2023-05-16 17:27 UTC, shawnkost commented on html-forms/index.html
> +            <label for="email"></label>
Your "Email" text on line 12 should be inside this `label`

2023-05-16 17:27 UTC, shawnkost commented on html-forms/index.html
> +      <select id="card" name="dropdown">
This should be a `label` & it should be attached to your `select` on line 20

2023-05-16 17:27 UTC, shawnkost commented on html-forms/index.html
> +       <input type="radio" id="firstcheck" name="check" value="html" /> HTML
Your HTML text should be inside the `label`. You can just put the `input` inside the `label`

2023-05-16 17:27 UTC, shawnkost commented on html-forms/index.html
> +        <input type="radio" id="secondcheck" name="check" value="css" /> CSS
Same note as above ^

2023-05-16 17:27 UTC, shawnkost commented on html-forms/index.html
> +    <input type="radio" id="thirdcheck" name="check" value="javascript" /> JavaScript
Same note as above ^

2023-05-16 17:27 UTC, shawnkost commented on html-forms/index.html
> + <input type="checkbox" id="sign" name="sign" value="signup"/> Sign me up!
The "Sign me up" text should be inside a `label` and it should be linked to this `input`

2023-05-16 17:27 UTC, shawnkost commented on html-forms/index.html
> + <div>Comments</div>
This should be a `label`, and it should be linked to your `textarea`

2023-05-17 22:25 UTC, shawnkost requested changes
A couple changes here David!

2023-05-17 22:25 UTC, shawnkost commented on html-forms/index.html
> +      <label for="card"></label>
The text inside your `div` on line 19 should be inside your `label` on line 21

2023-05-17 22:25 UTC, shawnkost commented on html-forms/index.html
> +  </label>
The text inside your `div` on line 48 should be inside your `label` on line 50

2023-05-18 15:35 UTC, shawnkost requested changes
Some more changes requested here David. A few things

1. The only content that should ever be inside a `label`, is text, or an `input`, `select`, etc. You can't put `div` elements or `span` elements
2. You either use the `for` attribute to connect `label`s to form control elements, OR you nest them inside the `label`, but you don't do both. It's one or the other.

Make sure you update my comments for this whole file.

2023-05-18 15:35 UTC, shawnkost commented on html-forms/index.html
> +        </div>
You can't put a `div` inside a `label`. The only thing inside a `label` should be the text itself and an `input` or some sort of form control element.

2023-05-18 15:35 UTC, shawnkost commented on html-forms/index.html
> +          <label for="card"><div>Why is coding cool?</div>
You can't put a `div` inside a `label`. The only thing inside a `label` should be the text itself and an `input` or some sort of form control element.

2023-05-18 15:35 UTC, shawnkost commented on html-forms/index.html
> +          </label>
It's either you use the `for` attribute, OR you nest the form control element inside the `label`. Not both. It's one or the other

2023-05-18 15:35 UTC, shawnkost commented on html-forms/index.html
> +          </label>
It's either you use the `for` attribute, OR you nest the form control element inside the `label`. Not both. It's one or the other

2023-05-18 15:35 UTC, shawnkost commented on html-forms/index.html
> +            <span>HTML</span>
No need for the `span`, just have the text in here directly

2023-05-18 15:35 UTC, shawnkost commented on html-forms/index.html
> +            <span>CSS</span>
No need for the `span`, just have the text in here directly

2023-05-18 15:35 UTC, shawnkost commented on html-forms/index.html
> +            <span>JavaScript</span>
No need for the `span`, just have the text in here directly

2023-05-18 15:35 UTC, shawnkost commented on html-forms/index.html
> +            <span>Sign me up!</span>
No need for the `span`, just have the text in here directly

2023-05-18 15:35 UTC, shawnkost commented on html-forms/index.html
> +          <label for="box"> <div>Comments</div>
You can't put a `div` inside a `label`. The only thing inside a `label` should be the text itself and an `input` or some sort of form control element.

2023-05-22 22:24 UTC, DavidKyong commented
Sorry, I accidentally commit it when I was not completed

2023-05-31 16:29 UTC, shawnkost approved these changes
👍🏻

2023-06-29 03:55 UTC, merged