Css canvas medical
DavidKyong/c0523-code-solutions pull request #38
Opened 2023-05-22 06:12 UTC by DavidKyong

<img width="1440" alt="Screenshot 2023-05-21 at 11 09 11 PM" src="https://github.com/DavidKyong/c0523-code-solutions/assets/77517004/d7759ee1-f7a6-4471-a74c-637a0b3fc646">
<img width="1434" alt="Screenshot 2023-05-21 at 11 09 22 PM" src="https://github.com/DavidKyong/c0523-code-solutions/assets/77517004/95c7b897-8fa6-49dc-b951-a82caa7d056d">
<img width="1437" alt="Screenshot 2023-05-21 at 11 09 31 PM" src="https://github.com/DavidKyong/c0523-code-solutions/assets/77517004/9dab1f8d-2505-429c-b241-953b42e280f9">

2023-05-23 18:42 UTC, shawnkost requested changes
Looks good David! I left one comment, but it doesn't need to be fixed, just pointing it out so that you're aware. Once we start getting into making things responsive, you will see the problem with the approach you have. Here's the thing that needs to actually be fixed.

1. Your image still seems too bright, try playing around with the `filter` values a bit more. You can adjust `brightness` `contrast` & `saturate` all in the `filter` property. Something like 
`filter: brightness(85%) contrast(75%) saturate(95%);`

2023-05-23 18:42 UTC, shawnkost commented on css-canvas-medical/styles.css
> +}
You want to be very careful using negative margin values. When you have such high margin values, it means you're usually doing something "hacky" to get this to work, rather than a more optimal solution. Rather than spacing all of these out with margin, why not utilize `justify-content` or `flex-basis` to adjust the width of each of these?

2023-05-24 23:22 UTC, DavidKyong commented on css-canvas-medical/styles.css
> +}
I will try to get more comfortable with justify-content and flex-basis!

2023-05-25 18:53 UTC, shawnkost approved these changes
👍🏻

2023-05-25 18:54 UTC, shawnkost approved these changes
👍🏻

2023-05-25 20:28 UTC, merged